/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package constructores;

import javax.swing.JOptionPane;

/**
 *
 * @author Aula 7 - Docente
 */
public class Ventana extends javax.swing.JFrame {

    //atributos
    Auto a = new Auto();
    public int contador = 0;
    
    public Ventana() {
        initComponents();
        
        //centrado de la app
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        chkTurbo = new javax.swing.JCheckBox();
        btnAcelerar = new javax.swing.JButton();
        btnFrenar = new javax.swing.JButton();
        btnInformar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca:");

        jLabel2.setText("Velocidad:");

        chkTurbo.setText("Turbo");

        btnAcelerar.setText("Acelerar");
        btnAcelerar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAcelerarKeyPressed(evt);
            }
        });

        btnFrenar.setText("Frenar");
        btnFrenar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnFrenarKeyPressed(evt);
            }
        });

        btnInformar.setText("Informar");
        btnInformar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnInformarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcelerar)
                        .addGap(43, 43, 43)
                        .addComponent(btnFrenar)
                        .addGap(33, 33, 33)
                        .addComponent(btnInformar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(chkTurbo)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(chkTurbo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcelerar)
                    .addComponent(btnFrenar)
                    .addComponent(btnInformar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInformarKeyPressed
        //capturo el contenido de las cajas de marca y velocidad
        //y las guardo en variables
        String marca = txtMarca.getText();
        int velocidad = Integer.parseInt(txtVelocidad.getText());
        
        //si es la 1ra vez q toco el boton de Informar...
        if (contador == 0) {
            //...seteo el estado inicial del auto
            a.marca = marca;
            a.velocidad = velocidad;
        }
        
        contador++;
        
        //muestro el estado del auto
        JOptionPane.showMessageDialog(this, a.toString());
        
        //ubico el foco del cursor en la caja de velocidad
        txtVelocidad.requestFocus();
    }//GEN-LAST:event_btnInformarKeyPressed

    private void btnFrenarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnFrenarKeyPressed
        //capturo y guardo el valor de la caja de velocidad
        int velocidad = Integer.parseInt(txtVelocidad.getText());
        
        //freno
        a.frenar(velocidad);
    }//GEN-LAST:event_btnFrenarKeyPressed

    private void btnAcelerarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAcelerarKeyPressed
        //capturo y guardo el valor de la caja de velocidad
        int velocidad = Integer.parseInt(txtVelocidad.getText());
        
        //si tengo el turbo puesto, acelero el doble
        if (chkTurbo.isSelected()) {
            a.acelerar(velocidad * 2);
        } else {
            a.acelerar(velocidad);
        }
        
    }//GEN-LAST:event_btnAcelerarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnFrenar;
    private javax.swing.JButton btnInformar;
    private javax.swing.JCheckBox chkTurbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtVelocidad;
    // End of variables declaration//GEN-END:variables
}
